export enum SoundEnum {
  Click_01 = 'Cub_Hi',
  Click_02 = 'Cub_low',
  Click_03 = 'Logic_Hi',
  Click_04 = 'Logic_low',

  Kick_01 = 'adt_kick_death',
  Kick_02 = 'adt_kick_huge',
  Kick_03 = 'adt_kick_large',
  Kick_04 = 'adt_kick_punchy',
  Kick_05 = 'adt_kick_rattle',
  Kick_06 = 'adt_kick_raw',
  Kick_07 = 'adt_kick_teeth',
  Kick_08 = 'adt_kick_thick',
  Kick_09 = 'adt_kick_thuddy',
  Kick_10 = 'adt_kick_warm',

  Snare_01 = 'adt_snare_vintage_1',
  Snare_02 = 'adt_snare_vintage_2',
  Snare_03 = 'adt_snare_vintage_3',
  Snare_04 = 'adt_snare_vintage_chain',
  Snare_05 = 'adt_snare_vintage_ghostnote',
  Snare_06 = 'adt_snare_vintage_rimshot',
  Snare_07 = 'adt_snare_woofy',
}

export const SOUND_DATA: Array<{ key: SoundEnum, value: string }> = [
  { key: SoundEnum.Click_01, value: 'Click 1' },
  { key: SoundEnum.Click_02, value: 'Click 2' },
  { key: SoundEnum.Click_03, value: 'Click 3' },
  { key: SoundEnum.Click_04, value: 'Click 4' },
  { key: SoundEnum.Kick_01, value: 'Kick 1' },
  { key: SoundEnum.Kick_02, value: 'Kick 2' },
  { key: SoundEnum.Kick_03, value: 'Kick 3' },
  { key: SoundEnum.Kick_04, value: 'Kick 4' },
  { key: SoundEnum.Kick_05, value: 'Kick 5' },
  { key: SoundEnum.Kick_06, value: 'Kick 6' },
  { key: SoundEnum.Kick_07, value: 'Kick 7' },
  { key: SoundEnum.Kick_08, value: 'Kick 8' },
  { key: SoundEnum.Kick_09, value: 'Kick 9' },
  { key: SoundEnum.Kick_10, value: 'Kick 10' },
  { key: SoundEnum.Snare_01, value: 'Snare 1' },
  { key: SoundEnum.Snare_02, value: 'Snare 2' },
  { key: SoundEnum.Snare_03, value: 'Snare 3' },
  { key: SoundEnum.Snare_04, value: 'Snare 4' },
  { key: SoundEnum.Snare_05, value: 'Snare 5' },
  { key: SoundEnum.Snare_06, value: 'Snare 6' },
  { key: SoundEnum.Snare_07, value: 'Snare 7' },
];
